# training:
epochs: 1001
batch_size: 2048
learning_rate: 0.0001 #1e-4
weight_decay: 0.00001 #1e-5
# transform:
use_stft: false
delay: 8
embedding: 8
# model:
handler: models.ImagenFew.handler
img_resolution: 8
unet_channels: 32
ch_mult: [1,2,2,4]
attn_resolution: [8,4,2]
diffusion_steps: 36
ema: true
ema_warmup: 100
# logging:
logging_iter: 100
tags: []
# Data
datasets_dir: ./data/
seq_len: 24
pretrain: false
datasets:
  - name: stock
    data: stock
  - name: energy
    data: energy
  - name: ETTh1
    data: ETTh1
    embed: timeF
    rel_path: TSF/ETT-small/ETTh1.csv
    features: M
    label_len: 7
    pred_len: 0
  - name: Exchange
    data: custom
    embed: timeF
    rel_path: TSF/exchange_rate/exchange_rate.csv
    features: M
    label_len: 8
    pred_len: 0
  - name: MSL
    data: MSL
    rel_path: MSL
  - name: PSM
    data: PSM
    rel_path: PSM
  - name: SMAP
    data: SMAP
    rel_path: SMAP
  - name: SMD
    data: SMD
    rel_path: SMD
  - name: SelfRegulationSCP2
    data: UEA
    rel_path: UEA/SelfRegulationSCP2
  - name: UWaveGestureLibrary
    data: UEA
    rel_path: UEA/UWaveGestureLibrary
  - name: ECG5000
    data: UEA
    rel_path: UEA/ECG5000
  - name: NonInvasiveFetalECGThorax1
    data: UEA
    rel_path: UEA/NonInvasiveFetalECGThorax1
  - name: Blink
    data: UEA
    rel_path: UEA/Blink
  - name: ElectricDevices
    data: UEA
    rel_path: UEA/ElectricDevices
  - name: Trace
    data: UEA
    rel_path: UEA/Trace
  - name: FordB
    data: UEA
    rel_path: UEA/FordB
  - name: EMOPain
    data: UEA
    rel_path: UEA/EMOPain
  - name: Chinatown
    data: UEA
    rel_path: UEA/Chinatown
  - name: SharePriceIncrease
    data: UEA
    rel_path: UEA/SharePriceIncrease
  - name: ETTm2
    data: ETTm2
    embed: timeF
    rel_path: TSF/ETT-small/ETTm2.csv
    features: M
    label_len: 7
    pred_len: 0
train_on_datasets:
  - ETTm2